<main class="flex-shrink-0">
    <!-- Header-->
    <header class="py-5">
        <div class="container px-5">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xxl-6">
                    <div class="text-center my-5">
                        <h1 class="fw-bolder mb-3"> Bienvenue sur CodeMasters, Notre mission est de vous aider à maîtriser HTML, PHP et CSS avec style!</h1>
                        <p class="lead fw-normal text-muted mb-4">

                        CodeMasters est bien plus qu'un simple site d'apprentissage en ligne. C'est un univers numérique où la créativité et le développement se rencontrent pour vous offrir une expérience d'apprentissage exceptionnelle.
                        </p>
                        <a class="btn btn-primary btn-lg" href="#scroll-target">Notre histoire</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- About section one-->
    <section class="py-5 bg-light" id="scroll-target">
        <div class="container px-5 my-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://elearningindustry.com/wp-content/uploads/2015/10/learning-technologies-fundamentals-part-1.jpg" alt="..." /></div>
                <div class="col-lg-6">
                    <h2 class="fw-bolder">Vous aurez besoin</h2>
                    <p class="lead fw-normal text-muted mb-0">D'un ordinateur et de votre plus jolie sourire.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- About section two-->
    <section class="py-5">
        <div class="container px-5 my-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://elearningindustry.com/wp-content/uploads/2015/10/learning-technologies-fundamentals-part-1.jpg" alt="..." /></div>
                <div class="col-lg-6">
                    <h2 class="fw-bolder">Croissance &amp; au-delà</h2>
                    <p class="lead fw-normal text-muted mb-0"> Une fois que vous aurez acquis les bases, vous pourrez relever des défis stimulants pour tester vos compétences et vous mesurer à d'autres codeurs du monde entier. Participez à des concours, gagnez des badges et montrez votre maîtrise en créant des projets impressionnants.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Team members section-->
    <section class="py-5 bg-light">
        <div class="container px-5 my-5">
            <div class="text-center">
                <h2 class="fw-bolder">Notre équipe</h2>
                <p class="lead fw-normal text-muted mb-5">Notre équipe se compose de développeurs expérimentés dans les langages HTML, PHP et CSS, chacun ayant une expertise spécifique et un fort engagement envers l'excellence technique. Que ce soit dans la conception de sites web élégants, la création de fonctionnalités complexes ou l'optimisation des performances, nos experts sont prêts à relever tous les défis.</p>
            </div>
            <div class="row gx-5 row-cols-1 row-cols-sm-2 row-cols-xl-4 justify-content-center">
                <div class="col mb-5 mb-5 mb-xl-0">
                    <div class="text-center">
                        <img class="img-fluid mb-4 px-4" src="my_pic.jfif" alt="..." />
                        <h5 class="fw-bolder">Oumaima Hmimdani</h5>
                        <div class="fst-italic text-muted">Foundateur &amp; CEO</div>
                    </div>
                </div>
            </div>
                <!--| ABOUT |--------------------------------------------------->
            <section id="about" class="container">
            <p>
            Étudiante en CyberSécuriter et Data Sciences. Intéressé et passionné par les Data Sciences pour participer à la création du monde de demain.
            </p>
            <p>
                <strong>Skills:</strong>
                <span class="badge badge-info" style ="background-color: blue;">Bootstrap</span>
                <span class="badge badge-info" style ="background-color: blue;">Ruby</span>
                <span class="badge badge-info" style ="background-color: blue;">Python</span>
                <span class="badge badge-info" style ="background-color: blue;">HTML</span>
                <span class="badge badge-info" style ="background-color: blue;">CSS</span>
                <span class="badge badge-info" style ="background-color: blue;">JavaScript</span>
                <span class="badge badge-info" style ="background-color: blue;">Node.js</span>
                <span class="badge badge-info" style ="background-color: blue;">Polymer.js</span>
                <span class="badge badge-info" style ="background-color: blue;">SQL</span>
            </p>
            </section>

            <!-- EXPERIENCE --------------------------------------------->
            <section id="experience" class="container">
            <h1>Experience</h1>
            <div class="card">
                <div class="card-header collapse show" data-toggle="collapse" data-target="#exp1">
                <div class="row">
                    <h5 class="col-md-8 mb-0">Alternante Data sciences</h5>
                    <em class="col-md-4 text-md-right">A partir de sep 2022 </em>
                </div>
                </div>
                <div class="card-block collapse" id="exp1">
                <h5>Fives Cortx</h5>
                <p>
                    Au sein d'une filiale d'un groupe multinationale, je fait une alternance de deux ans.
                </p>
                <p>
                    Mon rôle principal est d'appliquer des techniques et des méthodes analytiques avancées pour extraire des informations précieuses à partir de vastes ensembles de données. Vous travaillez en étroite collaboration avec l'équipe de Data Science, ainsi que d'autres départements de l'entreprise, pour comprendre les besoins spécifiques de l'organisation et développer des solutions basées sur les données.
                </p>
                </div>
            </div>
            
            <div class="card">
                <div class="card-header" data-toggle="collapse" data-target="#exp2">
                <div class="row">
                    <h5 class="col-md-8 mb-0">Intervenant pédagogique à domicile</h5>
                    <em class="col-md-4 text-md-right">A partir de Déc 2021</em>
                </div>
                </div>
                <div class="card-block collapse" id="exp2">
                <h5>Complétude</h5>
                <p>
                    Mon but principale expliquez les concepts difficiles, donnez des exemples pratiques, fournissez des exercices supplémentaires et répondez aux questions pour aider les élèves à améliorer leur compréhension et leurs performances scolaires.
                </p>
                <p>
                    Suivre régulièrement les progrès des élèves et évaluez leur évolution. Vous identifiez les points forts et les faiblesses persistantes, ajustez vos méthodes d'enseignement si nécessaire et fournissez des commentaires constructifs aux élèves et à leurs parents sur leurs performances et leurs efforts.
                </p>
                </div>
            </div>
            <div class="card">
                <div class="card-header" data-toggle="collapse" data-target="#exp3">
                <div class="row">
                    <h5 class="col-md-8 mb-0">Employé polyvalent</h5>
                    <em class="col-md-4 text-md-right">Mai 2022 - Sep 2022</em>
                </div>
                </div>
                <div class="card-block collapse" id="exp3">
                <h5>Pitaya</h5>
                <p>
                    Mes rôles principalent était d'accueillir les clients, les guider vers leur table et leur fournisser un service amical et professionnel. Vous prenez les commandes, répondez aux questions et veillez à ce que les clients soient satisfaits de leur expérience au restaurant.
                </p>
                <p>
                    Aidez à la préparation des plats en suivant les recettes et les directives du chef.
                </p>
                <p>
                    Participer à l'entretien général du restaurant en assurant la propreté des zones de service, des tables, des chaises et des équipements.
                </p>
                </div>
            </div>
            <div class="card">
                <div class="card-header" data-toggle="collapse" data-target="#exp4">
                <div class="row">
                    <h5 class="col-md-8 mb-0">Enquêtrice TCL</h5>
                    <em class="col-md-4 text-md-right">Mar 2022 - Mar 2022</em>
                </div>
                </div>
                <div class="card-block collapse" id="exp4">
                <h5>Toutes vos enquêtes</h5>
                <p>
                    Communiquez avec les passagers pour vérifier leur identité, recueillir des informations pertinentes et expliquer les règles et les procédures de paiement. Vous pouvez également répondre aux questions des passagers concernant les tarifs, les horaires ou d'autres informations liées aux transports en commun.
                </p>
                <p>
                    Rédigez des rapports détaillés sur les incidents de fraude détectés, y compris les informations sur les personnes impliquées, les circonstances de l'infraction et les mesures prises. Vous documentez également les procédures de contrôle, les tendances de fraude observées et les suggestions d'amélioration.
                </p>
                </div>
            </div>
            </section>
            
            <!-- CONTACT ----------------------------------------------------->

            <section class="container" id="contact">
            <h1>Contact</h1>
            <div class="row">
                <div class="col-sm-2">Phone:</div>
                <div class="col-sm-4">0729301313</div>
            </div>
            <div class="row">
                <div class="col-sm-2">Email:</div>
                <div class="col-sm-4"><a href="hmimdani.oumaima@gmail.com">hmimdani.oumaima@gmail.com</a></div>
            </div>
            <div class="row">
                <div class="col-sm-2">LinkedIn:</div>
                <div class="col-sm-4"><a href="linkedin.com/in/oumaima-hmimdani-3ba55a1b9/">https://www.linkedin.com/in/oumaima-hmimdani-3ba55a1b9/</a></div>
            </div>
            </section>
        </div>
    </section>


</main>
<!-- Footer-->
