<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Nos Products</h2>
                    <p class="lead fw-normal text-muted mb-5">CodeMasters propose des cours interactifs et progressifs pour apprendre HTML, PHP et CSS. Les leçons claires et structurées, accompagnées d'exemples concrets et d'exercices pratiques, vous guident à travers les concepts fondamentaux et avancés de chaque langage.</p>
                </div>
            </div>
        </div>
        <div class="row gx-5">
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://static.wixstatic.com/media/72c0b2_58cde2ebb708454fb4aa74c2b5c1b648~mv2.png/v1/fit/w_1000%2Ch_608%2Cal_c%2Cq_80,enc_auto/file.jpg" alt="..." />
                    <div class="card-body p-4">
                        <a class="text-decoration-none link-dark stretched-link" href="#!">
                            <h5 class="card-title mb-3">Cours proposés</h5>
                        </a>
                        <p class="card-text mb-0">Introduction au développement web (HTML, CSS, PHP), Design avancé (CSS, responsive design), Backend development (PHP, MySQL, sécurité), Développement web avancé (frameworks PHP, JavaScript), Sites e-commerce (paniers d'achat, paiement en ligne). Des cours complets pour acquérir une expertise dans le développement web en utilisant HTML, CSS et PHP.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" style="width: 40px;
    height: 40px;" src="https://www.eventfulnigeria.com/wp-content/uploads/2021/04/Avatar-PNG-Free-Download.png" alt="..." />

                                <div class="small">
                                    <div class="fw-bold">Hmimdani Oumaima</div>
                                    <div class="text-muted">May 12, 2023</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEJwAWSIZVyOuAsztq1eMRQtve_WyJCki_ug&usqp=CAU" alt="..." />
                    <div class="card-body p-4">
                        <a class="text-decoration-none link-dark stretched-link" href="#!">
                            <h5 class="card-title mb-3">Projet évaluer</h5>
                        </a>
                        <p class="card-text mb-0">Site de portfolio personnel (HTML, CSS, PHP), Blog personnel (HTML, CSS, PHP), Site de commerce électronique simple (HTML, CSS, PHP), Site de réservation d'événements (HTML, CSS, PHP), Site d'actualités ou de blog thématique (HTML, CSS, PHP). Des projets pratiques pour appliquer et développer les compétences en HTML, CSS et PHP, en créant des sites web personnalisés et fonctionnels.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" style="width: 40px;
    height: 40px;" src="https://www.eventfulnigeria.com/wp-content/uploads/2021/04/Avatar-PNG-Free-Download.png" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">Hmimdani Oumaima</div>
                                    <div class="text-muted">May 15, 2023</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://i.ytimg.com/vi/27JtRAI3QO8/maxresdefault.jpg" alt="..." />
                    <div class="card-body p-4">
                        <a class="text-decoration-none link-dark stretched-link" href="#!">
                            <h5 class="card-title mb-3">Notions avancées</h5>
                        </a>
                        <p class="card-text mb-0">HTML sémantique, animations CSS, POO en PHP, interactions entre HTML, CSS et PHP, sécurité et performances web. Approfondissez vos compétences en créant des sites web optimisés, sécurisés et interactifs en utilisant HTML, CSS et PHP.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" style="width: 40px;
    height: 40px;" src="https://www.eventfulnigeria.com/wp-content/uploads/2021/04/Avatar-PNG-Free-Download.png" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">Hmimdani Oumaima</div>
                                    <div class="text-muted">May 18, 2023</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>